export type {
  ColorFunctionLiteral,
  ColorFunctionMode,
  ColorFunctionState,
  ColorFunctionString,
  ColorFunctionStringMap,
  ColorMixLiteral,
  ColorMixState,
  ColorMixString,
  ColorsOf,
  HueMethod,
  KindOf,
  LightDarkLiteral,
  LightDarkState,
  LightDarkString,
  MixColorSpace,
  MixSpaceOf,
  RelativeColorLiteral,
  RelativeColorState,
  RelativeColorString,
  RelativeFn,
  RelativeFnOf,
} from "./color-function.types"
export { cssColorFn } from "./color-function.types"
