import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const registryPath = resolve(__dirname, "../registry.json")
let registry
try {
  registry = JSON.parse(readFileSync(registryPath, "utf8"))
} catch (err) {
  throw new Error(
    `build-nav: cannot read/parse ${registryPath}: ${err.message}`,
  )
}
if (!Array.isArray(registry.items)) {
  throw new Error("build-nav: registry.json is missing an `items` array")
}

// Items with no `files` are meta-bundles (e.g. "all"), not actual components.
const items = registry.items
  .filter((it) => Array.isArray(it.files) && it.files.length > 0)
  .map((it) => ({
    name: it.name,
    title: it.title,
    description: it.description,
    href: `/${it.name}/`,
  }))

const out = `// AUTO-GENERATED by scripts/build-nav.mjs. Do not edit.
export interface NavItem {
  name: string
  title: string
  description: string
  href: \`/\${string}/\`
}

export const NAV = ${JSON.stringify(items, null, 2)} as const satisfies readonly NavItem[]
`

const outDir = resolve(__dirname, "../src/generated")
mkdirSync(outDir, { recursive: true })
writeFileSync(resolve(outDir, "nav.ts"), out)

console.log(`Wrote ${items.length} nav items to src/generated/nav.ts`)
